minify: true

scheme: Gemini

menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  sitemap: /sitemap.xml || fa fa-sitemap

avatar:
  url: /images/avatar.webp
  rounded: true

social:
  GitHub: https://github.com/kernel-panic-1024 || fab fa-github
  E-Mail: mailto:kernel_panic-1024@protonmail.com || fa fa-envelope

math:
  every_page: true
  katex:
    enable: true

post_meta:
  updated_at:
    enable: false
