minify: true

scheme: Gemini

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  categories: /categories/ || fa fa-th
  tags: /tags/ || fa fa-tags
  sitemap: /sitemap.xml || fa fa-sitemap

avatar:
  url: /images/avatar.webp
  rounded: true

social:
  GitHub: https://github.com/krn1pnc || fab fa-github
  E-Mail: mailto:krn1pnc@outlook.com || fa fa-envelope

creative_commons:
  license: by-nc-sa
  size: small
  sidebar: true
  language: deed.zh

math:
  every_page: true
  katex:
    enable: true

codeblock:
  theme:
    light: base16/tomorrow-night
    dark: base16/tomorrow-night
  copy_button:
    enable: true

post_meta:
  updated_at:
    enable: false
