minify: true

scheme: Gemini

menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  tags: /tags/ || fa fa-tags
  sitemap: /sitemap.xml || fa fa-sitemap

avatar:
  url: /images/avatar.webp
  rounded: true

social:
  GitHub: https://github.com/krn1pnc || fab fa-github
  E-Mail: mailto:krn1pnc@outlook.com || fa fa-envelope

math:
  every_page: true
  katex:
    enable: true

post_meta:
  updated_at:
    enable: false
